# .github/workflows/hex_context_toolkit.yml

name: Publish hex context

on:
  push:
    # Change this if you have a different default branch, you can also add other branches if you want to test this before merging
    branches: [ 'main' ] 
  pull_request:

jobs:
  publish_hex_context:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Upload guide files
      uses: hex-inc/action-context-toolkit@v1
      with:
        config_file: hex_context.config.json
        token: ${{ secrets.HEX_API_TOKEN }} # Set this in your repository settings
        hex_url: https://rc.hex.tech

        # optional configuration
        # publish_guides: true # publish guides automatically (default true)
        # delete_untracked_guides: true # removes guides from hex that were also deleted in your repository (default true)
        # hex_url: https://app.hex.tech # by default, is https://app.hex.tech - change if you have a single tenant hosted stack
